### ISSUE TITLE
Possible bug: _get_cepstra does not use magnitude spectrum

### ISSUE THREAD

**Issue by NickleDave** [theresekoch/avn#12]
Hi @theresekoch hope you are doing good.

I just wanted to let you know about a possible bug I think I might have spotted.

I think that `_get_cepstra` should be taking the absolute value of the log here, to get the magnitude spectrum before it computes the cepstrum from that:
https://github.com/theresekoch/avn/blob/5c429ab9f8a42f523fb143fe073feeedb16397c1/avn/acoustics.py#L363

I documented it in (probably too much) detail here:
https://github.com/vocalpy/vocalpy/issues/122#issue-2124142382

The tl;dr is that the cepstrum is defined as the log of the absolute value of the DFT--the magnitude spectrum--and that the Matlab function `rceps` used in SAT follows this definition.
*Not* taking the absolute value does actually lead to a change in feature values (not huge, but noticeable, and I haven't tested whether it affects any downstream analysis).
See also this implementation that likewise takes the absolute value:
https://github.com/python-acoustics/python-acoustics/blob/99d79206159b822ea2f4e9d27c8b2fbfeb704d38/acoustics/cepstrum.py#L146

Since you've done 99% of the work of translating SAT feature extraction to Python here, I thought the least I could do was let you know about this minor thing.

If you agree this should be changed, I'm happy to make a PR--since it's like a one-line fix. Hope this is helpful

**Comment by theresekoch** [comment]
Hi David! Thanks for letting me know and for looking through the code so carefully! I think there might be some confusion as to where to take the absolute value in the cepstrum calculation. As you stated, the SAT implementation takes the log of the absolute value of the spectrum, then computes the ifft. That is what `_get_cepstra` is doing. I guess the naming of the variables isn't explicitly reflecting that, but the `spectrum` variable  in line 360 is already the `abs(spectra)`.  https://github.com/theresekoch/avn/blob/5c429ab9f8a42f523fb143fe073feeedb16397c1/avn/acoustics.py#L360 So `log_spectrum` is effectively `log(abs(spectra))`, and therefore `cepstrum` is `ifft(log(abs(spectra)))`. 

Taking the absolute value of the log_spectrum (`ifft(abs(log(spectra)))`), rather than the absolute value of the spectrum before taking the log (`ifft(log(abs(spectra)))`) gives results that are inconsistent with SAT. The current implementation gives goodness of pitch scores that are consistent with SAT.

**Comment by NickleDave** [comment]
:exclamation: 

ah ok, got it -- I think I must have dropped this line when adapting from your code in an attempt to vectorize it. So, totally my fault :innocent: 

Thank you for explaining! Will close this
